title: EbMS Adapter
lang: en
description: EbMS adapter for Java
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  eluinstra
markown: GFM
# theme: jekyll-rtd-theme
remote_theme: rundocs/jekyll-rtd-theme

repository: eluinstra/ebms-admin

# nav_version: true
# edit: true

copyright:
  revision: true

readme_index:
  with_frontmatter: true
