title: EbMS Adapter
lang: en
description: EbMS adapter for Java

# theme: jekyll-rtd-theme
remote_theme: rundocs/jekyll-rtd-theme

repository: eluinstra/ebms-admin

addons_branch: true
edit: true

copyright:
  revision: true

addons:
  - github
  - i18n
  - plugins
  - analytics

# sort
readme_index:
  with_frontmatter: true

sass:
  style: compressed

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
  - assets/images/src

# optional plugins
plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
